/**
 * Weekly Insight Card — AI Coach Summary
 * ═══════════════════════════════════════
 *
 * WHAT IT SHOWS:
 * ──────────────
 * A styled card with the AI-generated weekly coaching insight.
 * Includes 3 highlights and one actionable suggestion.
 *
 * HOW IT CONNECTS:
 * ────────────────
 * useWeeklyInsight() hook → GET /api/ai/weekly-insight
 *   → ai.service.generateWeeklyInsight()
 *     → reads 7 days of nutrition/workout/weight data (Step 3)
 *     → sends to LLM via fallback chain
 *     → cached in WeeklyInsight table
 *
 * STATES:
 * ───────
 * loading → shimmer skeleton
 * success → insight card with text, highlights, suggestion
 * error → friendly error message
 * no data → "Log more data to get your insight" message
 */

"use client";

import { useWeeklyInsight } from "@/lib/hooks/use-weekly-insight";

export function WeeklyInsightCard() {
  const { data, isLoading, isError, error } = useWeeklyInsight();

  // Loading skeleton
  if (isLoading) {
    return (
      <div className="bg-surface border border-border rounded-xl p-4 space-y-3">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-primary/20 rounded-lg animate-pulse" />
          <div className="h-5 w-32 bg-border rounded animate-pulse" />
        </div>
        <div className="space-y-2">
          <div className="h-4 bg-border rounded animate-pulse" />
          <div className="h-4 bg-border rounded animate-pulse w-5/6" />
          <div className="h-4 bg-border rounded animate-pulse w-4/6" />
        </div>
      </div>
    );
  }

  // Error state
  if (isError) {
    return (
      <div className="bg-surface border border-border rounded-xl p-4">
        <div className="flex items-center gap-2 mb-2">
          <span className="text-lg">🤖</span>
          <h3 className="font-semibold text-sm text-text-primary">
            AI Coach
          </h3>
        </div>
        <p className="text-sm text-text-muted">
          {error?.message || "Could not generate your weekly insight."}
        </p>
        <p className="text-xs text-text-muted mt-1">
          Try again later or log more data this week.
        </p>
      </div>
    );
  }

  // No data yet
  if (!data) return null;

  return (
    <div className="bg-surface border border-primary/20 rounded-xl p-4 space-y-3">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 bg-gradient-to-br from-primary/20 to-accent/20 rounded-lg flex items-center justify-center">
            <span className="text-sm">🤖</span>
          </div>
          <div>
            <h3 className="font-semibold text-sm text-text-primary">
              Weekly Insight
            </h3>
            <p className="text-[10px] text-text-muted">
              Week of {data.weekStart}
            </p>
          </div>
        </div>
        {data.cached && (
          <span className="text-[9px] bg-surface border border-border text-text-muted px-2 py-0.5 rounded-full">
            Cached
          </span>
        )}
      </div>

      {/* Insight text */}
      <p className="text-sm text-text-secondary leading-relaxed">
        {data.insight}
      </p>

      {/* Highlights */}
      {data.highlights && data.highlights.length > 0 && (
        <div className="space-y-1.5">
          {data.highlights.map((h, i) => (
            <div key={i} className="flex items-start gap-2 text-xs">
              <span className="text-primary mt-0.5">
                {i === 0 ? "💪" : i === 1 ? "📊" : "🎯"}
              </span>
              <span className="text-text-secondary">{h}</span>
            </div>
          ))}
        </div>
      )}

      {/* Suggestion */}
      {data.suggestion && (
        <div className="bg-primary/5 border border-primary/10 rounded-lg p-3">
          <p className="text-xs text-text-muted mb-0.5">
            💡 Suggestion for next week
          </p>
          <p className="text-sm text-text-primary">{data.suggestion}</p>
        </div>
      )}

      {/* Footer */}
      <p className="text-[9px] text-text-muted text-right">
        Generated by {data.provider}
      </p>
    </div>
  );
}
