"use client";

/**
 * Progress Page — Weight tracking and goal progress
 * ══════════════════════════════════════════════════
 *
 * Shows:
 * 1. Weight log input (quick entry for today)
 * 2. Stats cards (starting, current, change, log count)
 * 3. Weight trend chart (SVG line chart)
 *
 * ADAPTIVE TDEE:
 * After 14+ weight log entries, the progress page shows that
 * Adaptive TDEE is available. The adaptive-tdee.ts engine (Step 2)
 * can calculate the user's real TDEE from actual weight change.
 *
 * WEEKLY AI INSIGHT (Step 4):
 * Shows a personalised coaching summary generated by the LLM.
 * Reads 7 days of nutrition/workout/weight data and produces
 * highlights + actionable suggestion.
 */

import { useProgressData } from "@/lib/hooks/use-progress";
import { WeightLogInput } from "./_components/weight-log-input";
import { WeightChart } from "./_components/weight-chart";
import { StatsCards } from "./_components/stats-cards";
import { WeeklyInsightCard } from "./_components/weekly-insight-card";

export default function ProgressPage() {
  const { data: progress, isLoading } = useProgressData();

  return (
    <div className="space-y-4">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold font-[family-name:var(--font-outfit)]">
          Progress
        </h1>
        <p className="text-text-secondary text-sm mt-0.5">
          Track your body transformation
        </p>
      </div>

      {/* Weight Log Input */}
      <WeightLogInput />

      {/* Loading */}
      {isLoading && (
        <div className="space-y-3">
          {[1, 2, 3].map((i) => (
            <div
              key={i}
              className="bg-surface rounded-2xl p-6 border border-border animate-pulse h-24"
            />
          ))}
        </div>
      )}

      {progress && (
        <>
          {/* Stats Cards */}
          <StatsCards
            startWeight={progress.startWeight}
            currentWeight={progress.currentWeight}
            totalChange={progress.totalChange}
            logCount={progress.logCount}
            canUseAdaptiveTDEE={progress.canUseAdaptiveTDEE}
          />

          {/* Weight Chart */}
          <WeightChart
            history={progress.history}
            targetWeight={progress.activeGoal?.targetValue}
          />

          {/* Weekly AI Insight (Step 4) */}
          <WeeklyInsightCard />

          {/* Adaptive TDEE Notice */}
          {progress.canUseAdaptiveTDEE && (
            <div className="bg-primary/5 border border-primary/20 rounded-2xl p-4">
              <p className="text-sm font-semibold text-primary">
                ✨ Adaptive TDEE Available
              </p>
              <p className="text-xs text-text-secondary mt-1">
                You have {progress.logCount} weight logs. The engine can now
                calculate your real TDEE from actual data — more accurate than
                any formula.
              </p>
            </div>
          )}
        </>
      )}
    </div>
  );
}
