"use client";

/**
 * Progress Page — Weight tracking and goal progress
 * ══════════════════════════════════════════════════
 *
 * Shows:
 * 1. Weight log input (quick entry for today)
 * 2. Stats cards (starting, current, change, log count)
 * 3. Weight trend chart (SVG line chart)
 *
 * LAYOUT (laptop): 12-col grid — log + stats on top, full-width chart,
 * insight + adaptive notice side-by-side so the wide shell is filled.
 *
 * ADAPTIVE TDEE:
 * After 14+ weight log entries, the progress page shows that
 * Adaptive TDEE is available. The adaptive-tdee.ts engine (Step 2)
 * can calculate the user's real TDEE from actual weight change.
 *
 * WEEKLY AI INSIGHT (Step 4):
 * Shows a personalised coaching summary generated by the LLM.
 * Reads 7 days of nutrition/workout/weight data and produces
 * highlights + actionable suggestion.
 */

import { useProgressData } from "@/lib/hooks/use-progress";
import { WeightLogInput } from "./_components/weight-log-input";
import { WeightChart } from "./_components/weight-chart";
import { StatsCards } from "./_components/stats-cards";
import { WeeklyInsightCard } from "./_components/weekly-insight-card";

export default function ProgressPage() {
  const { data: progress, isLoading } = useProgressData();

  return (
    <div className="space-y-4 lg:space-y-5">
      {/* Header */}
      <div>
        <h1 className="text-2xl lg:text-3xl font-bold font-[family-name:var(--font-outfit)]">
          Progress
        </h1>
        <p className="text-text-secondary text-sm mt-0.5">
          Track your body transformation
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 lg:grid-cols-12 lg:gap-5 lg:items-start">
        {/* Weight Log Input */}
        <div className="lg:col-span-4">
          <WeightLogInput />
        </div>

        {/* Loading */}
        {isLoading && (
          <div className="lg:col-span-8 space-y-3">
            {[1, 2].map((i) => (
              <div
                key={i}
                className="bg-surface rounded-2xl p-6 border border-border animate-pulse h-24"
              />
            ))}
          </div>
        )}

        {progress && (
          <>
            {/* Stats Cards */}
            <div className="lg:col-span-8">
              <StatsCards
                startWeight={progress.startWeight}
                currentWeight={progress.currentWeight}
                totalChange={progress.totalChange}
                logCount={progress.logCount}
                canUseAdaptiveTDEE={progress.canUseAdaptiveTDEE}
              />
            </div>

            {/* Weight Chart — full width */}
            <div className="lg:col-span-12">
              <WeightChart
                history={progress.history}
                targetWeight={progress.activeGoal?.targetValue}
              />
            </div>

            {/* Recent Workouts — last 7 days, refreshed when a session is
                finished (finish mutation invalidates the progress cache) */}
            <div className="lg:col-span-12">
              <div className="bg-surface rounded-2xl border border-border overflow-hidden">
                <p className="px-4 lg:px-5 pt-4 pb-2 text-sm font-semibold text-text-secondary uppercase tracking-wider">
                  Recent Workouts{" "}
                  <span className="normal-case font-normal text-text-muted">
                    · last 7 days
                  </span>
                </p>
                {progress.recentWorkouts?.length ? (
                  <div className="divide-y divide-border">
                    {progress.recentWorkouts.map((w) => (
                      <div
                        key={w.id}
                        className="p-3 px-4 lg:px-5 flex items-center gap-3"
                      >
                        <span className="text-base leading-none">🏋️</span>
                        <span className="flex-1 min-w-0">
                          <span className="block text-sm font-medium text-text-primary truncate">
                            {w.exercises.length > 0
                              ? w.exercises.join(", ")
                              : "Workout"}
                          </span>
                          <span className="block text-xs text-text-muted">
                            {new Date(w.date).toLocaleDateString(undefined, {
                              weekday: "short",
                              day: "numeric",
                              month: "short",
                            })}
                            {" · "}
                            {w.totalSets} set{w.totalSets !== 1 ? "s" : ""}
                            {w.durationMin ? ` · ${w.durationMin} min` : ""}
                            {w.caloriesBurnedLow && w.caloriesBurnedHigh
                              ? ` · ≈${w.caloriesBurnedLow}–${w.caloriesBurnedHigh} kcal`
                              : ""}
                          </span>
                        </span>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="px-4 lg:px-5 pb-4 text-sm text-text-muted">
                    No workouts in the last 7 days — log one from the Workout
                    tab and it will show up here.
                  </p>
                )}
              </div>
            </div>

            {/* Weekly AI Insight (Step 4) */}
            <div
              className={
                progress.canUseAdaptiveTDEE ? "lg:col-span-7" : "lg:col-span-12"
              }
            >
              <WeeklyInsightCard />
            </div>

            {/* Adaptive TDEE Notice */}
            {progress.canUseAdaptiveTDEE && (
              <div className="lg:col-span-5">
                <div className="bg-primary/5 border border-primary/20 rounded-2xl p-4 lg:p-5 h-full">
                  <p className="text-sm font-semibold text-primary">
                    ✨ Adaptive TDEE Available
                  </p>
                  <p className="text-xs text-text-secondary mt-1 leading-relaxed">
                    You have {progress.logCount} weight logs. The engine can now
                    calculate your real TDEE from actual data — more accurate than
                    any formula.
                  </p>
                </div>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
